install_data('Films.foot', 'Films.head', 'Records.foot', 'Records.head',
             'Genres.dat', 'Genres.dat.de', 'Genres.dat.es',
             'de.png', 'en.png', 'es.png', 'fi.png', 'fr.png', 'in.png', 'it.png', 'no.png', 'pl.png', 'pt.png',
             'rs.png', 'sv.png',
             install_dir: pkgdatadir)
install_data('CDManager.desktop', install_dir: datadir / 'applications')
install_data('CDManager.png', install_dir: datadir / 'icons')
