#ifndef DB_H
#define DB_H

// This file is part of CDManager
//
// CDManager is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// CDManager is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with CDManager.  If not, see <http://www.gnu.org/licenses/>.

#include <sstream>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

/**Base class for the access to the database.

   It does the database independent work: It stores the result of a query,
   iterates over it, converts the columns and builds (standard SQL)
   statements.

   The derived classes (like DBMySQL or DBPostgres) handle the specifics of
   the used database, like connecting, executing a query and escaping values.

   All errors are reported as std::exception (usually std::runtime_error).
 */
class Database {
  public:
    /// Column names with their values for insert () and update (). Values are
    /// inserted as passed, so texts must be quoted before (see quote ())
    class Values {
      public:
        /// Adds a column with its value
        /// \param column Name of the column
        /// \param value Value (as SQL literal) for the column
        /// \returns Values& Reference to this, to allow chaining
        template <typename T> Values& operator()(const char* column, const T& value) {
            std::ostringstream str;
            str << value;
            entries.emplace_back(column, str.str());
            return *this;
        }

        using const_iterator = std::vector<std::pair<std::string, std::string>>::const_iterator;
        [[nodiscard]] const_iterator begin() const { return entries.begin(); }
        [[nodiscard]] const_iterator end() const { return entries.end(); }
        [[nodiscard]] bool empty() const { return entries.empty(); }

      private:
        std::vector<std::pair<std::string, std::string>> entries;
    };

    static Database* create();
    virtual ~Database() = default;

    virtual void connect(const char* db, const char* user, const char* pwd) = 0;
    virtual void close() = 0;
    [[nodiscard]] virtual bool connected() const = 0;

    void execute(const char* query) pre(query) pre(connected());
    void execute(const std::string& query) { execute(query.c_str()); }
    void insert(const char* table, const Values& values) pre(table) pre(!values.empty());
    void update(const char* table, const Values& values, const std::string& where)
        pre(table) pre(!values.empty()) pre(where.size());

    /// Returns the ID generated by the last INSERT into a table with an
    /// automatically generated ID-column
    virtual long getIDOfInsert() = 0;

    [[nodiscard]] unsigned int resultSize() const { return rows.size(); }
    [[nodiscard]] bool hasData() const { return current < rows.size(); }
    void getNextResultRow() { ++current; }
    [[nodiscard]] const std::string& getResultColumnAsBlob(unsigned int column) const;
    [[nodiscard]] const std::string& getResultColumnAsString(unsigned int column) const;
    [[nodiscard]] unsigned int getResultColumnAsUInt(unsigned int column) const;
    [[nodiscard]] int getResultColumnAsInt(unsigned int column) const;

    /// Escapes the passed text, so it can be used inside a (single-quoted)
    /// SQL string
    [[nodiscard]] virtual std::string escapeDBValue(const std::string& value) const = 0;
    /// Returns the passed binary data as SQL literal
    [[nodiscard]] virtual std::string quoteBlob(const std::string& value) const = 0;
    [[nodiscard]] std::string quote(const std::string& value) const;

    Database(const Database& other) = delete("Database holds a connection");
    Database& operator=(const Database& other) = delete("Database holds a connection");

  protected:
    /// One row of a result; NULL values are stored as empty strings
    using Row = std::vector<std::string>;

    Database() = default;

    /// Executes the passed query and stores the returned rows in result
    virtual void query(const char* query, std::vector<Row>& result) = 0;

  private:
    [[nodiscard]] const std::string& column(unsigned int column) const pre(hasData()) pre(column < rows[current].size());

    std::vector<Row> rows;
    unsigned int current{0};
};

#endif
