#ifndef DB_H
#define DB_H

// This file is part of CDManager
//
// CDManager is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// CDManager is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with CDManager.  If not, see <http://www.gnu.org/licenses/>.


#include <string>
#include <vector>
#include <sstream>
#include <utility>
#include <stdexcept>


/**Base class for the access to the database.

   It does the database independent work: It stores the result of a query,
   iterates over it, converts the columns and builds (standard SQL)
   statements.

   The derived classes (like DBMySQL or DBPostgres) handle the specifics of
   the used database, like connecting, executing a query and escaping values.

   All errors are reported as std::exception (usually std::runtime_error).
 */
class Database {
 public:
   /// Column names with their values for insert () and update (). Values are
   /// inserted as passed, so texts must be quoted before (see quote ())
   class Values {
    public:
      /// Adds a column with its value
      /// \param column Name of the column
      /// \param value Value (as SQL literal) for the column
      /// \returns Values& Reference to this, to allow chaining
      template <typename T>
      Values& operator() (const char* column, const T& value) {
	 std::ostringstream str;
	 str << value;
	 entries.push_back (std::make_pair (std::string (column), str.str ()));
	 return *this;
      }

      typedef std::vector<std::pair<std::string, std::string> >::const_iterator const_iterator;
      const_iterator begin () const { return entries.begin (); }
      const_iterator end () const { return entries.end (); }
      bool empty () const { return entries.empty (); }

    private:
      std::vector<std::pair<std::string, std::string> > entries;
   };

   static Database* create ();
   virtual ~Database ();

   virtual void connect (const char* db, const char* user, const char* pwd) = 0;
   virtual void close () = 0;
   virtual bool connected () const = 0;

   void execute (const char* query);
   void execute (const std::string& query) { execute (query.c_str ()); }
   void insert (const char* table, const Values& values);
   void update (const char* table, const Values& values, const std::string& where);

   /// Returns the ID generated by the last INSERT into a table with an
   /// automatically generated ID-column
   virtual long getIDOfInsert () = 0;

   unsigned int resultSize () const { return rows.size (); }
   bool hasData () const { return current < rows.size (); }
   void getNextResultRow () { ++current; }
   const std::string& getResultColumnAsBlob (unsigned int column) const;
   const std::string& getResultColumnAsString (unsigned int column) const;
   unsigned int getResultColumnAsUInt (unsigned int column) const;
   int getResultColumnAsInt (unsigned int column) const;

   /// Escapes the passed text, so it can be used inside a (single-quoted)
   /// SQL string
   virtual std::string escapeDBValue (const std::string& value) const = 0;
   /// Returns the passed binary data as SQL literal
   virtual std::string quoteBlob (const std::string& value) const = 0;
   std::string quote (const std::string& value) const;

 protected:
   /// One row of a result; NULL values are stored as empty strings
   typedef std::vector<std::string> Row;

   Database ();

   /// Executes the passed query and stores the returned rows in result
   virtual void query (const char* query, std::vector<Row>& result) = 0;

 private:
   Database (const Database& other);
   const Database& operator= (const Database& other);

   const std::string& column (unsigned int column) const;

   std::vector<Row> rows;
   unsigned int current;
};

#endif
