//PROJECT     : CDManager
//SUBSYSTEM   : Database/MySQL
//REFERENCES  :
//TODO        :
//BUGS        :
//AUTHOR      : Markus Schwab
//CREATED     : 25.09.2026
//COPYRIGHT   : Copyright (C) 2026

// This file is part of CDManager
//
// CDManager is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// CDManager is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with CDManager.  If not, see <http://www.gnu.org/licenses/>.


#include <cdmgr-cfg.h>

#include <cstring>

#include <mysql.h>

#include <YGP/Check.h>
#include <YGP/Trace.h>

#include "DBMySQL.h"


//-----------------------------------------------------------------------------
/// Defaultconstructor
//-----------------------------------------------------------------------------
DBMySQL::DBMySQL () : mysql (NULL) {
}

//-----------------------------------------------------------------------------
/// Destructor
//-----------------------------------------------------------------------------
DBMySQL::~DBMySQL () {
   close ();
}

//-----------------------------------------------------------------------------
/// Connects to the database on the local host
/// \param db Name of database
/// \param user User to use for the DB
/// \param pwd Password of user
/// \throw std::exception In case of an error
//-----------------------------------------------------------------------------
void DBMySQL::connect (const char* db, const char* user, const char* pwd) {
   TRACE9 ("DBMySQL::connect (const char* (3x) - " << db << " from " << user);
   Check2 (!mysql);

   mysql = mysql_init (NULL);
   if (!mysql)
      throw std::runtime_error ("Out of memory initialising MySQL");
   if (!mysql_real_connect (mysql, NULL, user, pwd, db, 0, NULL, 0)) {
      std::runtime_error error (mysql_error (mysql));
      close ();
      throw error;
   }
}

//-----------------------------------------------------------------------------
/// Closes the connection to the database
//-----------------------------------------------------------------------------
void DBMySQL::close () {
   TRACE9 ("DBMySQL::close ()");
   if (mysql) {
      mysql_close (mysql);
      mysql = NULL;
   }
}

//-----------------------------------------------------------------------------
/// Checks if the connection to the database is established
/// \returns bool True, if connected
//-----------------------------------------------------------------------------
bool DBMySQL::connected () const {
   return mysql != NULL;
}

//-----------------------------------------------------------------------------
/// Executes the passed query
/// \param query Query to execute
/// \param result Vector receiving the returned rows
/// \throw std::exception In case of an error
//-----------------------------------------------------------------------------
void DBMySQL::query (const char* query, std::vector<Row>& result) {
   Check2 (mysql);
   if (mysql_real_query (mysql, query, strlen (query)))
      throw std::runtime_error (mysql_error (mysql));

   MYSQL_RES* res (mysql_store_result (mysql));
   if (!res) {
      if (mysql_field_count (mysql))            // Query should have returned data
	 throw std::runtime_error (mysql_error (mysql));
      return;
   }

   unsigned int cColumns (mysql_num_fields (res));
   result.reserve (mysql_num_rows (res));
   MYSQL_ROW row;
   while ((row = mysql_fetch_row (res)) != NULL) {
      unsigned long* lengths (mysql_fetch_lengths (res));
      result.push_back (Row ());
      Row& target (result.back ());
      target.reserve (cColumns);
      for (unsigned int i (0); i < cColumns; ++i)
	 target.push_back (row[i] ? std::string (row[i], lengths[i]) : std::string ());
   }
   mysql_free_result (res);
}

//-----------------------------------------------------------------------------
/// Returns the ID generated by the last INSERT
/// \returns long Generated ID
//-----------------------------------------------------------------------------
long DBMySQL::getIDOfInsert () {
   Check2 (mysql);
   return mysql_insert_id (mysql);
}

//-----------------------------------------------------------------------------
/// Escapes the passed text for the use inside a SQL string
/// \param value Text to escape
/// \returns std::string Escaped text
//-----------------------------------------------------------------------------
std::string DBMySQL::escapeDBValue (const std::string& value) const {
   Check2 (mysql);
   std::string conv ((value.length () << 1) + 1, '\0');
   conv.resize (mysql_real_escape_string (mysql, &conv[0], value.data (), value.length ()));
   return conv;
}

//-----------------------------------------------------------------------------
/// Returns the passed binary data as SQL literal
/// \param value Data to quote
/// \returns std::string SQL literal
/// \remarks MySQL stores binary data in BLOBs like text
//-----------------------------------------------------------------------------
std::string DBMySQL::quoteBlob (const std::string& value) const {
   return quote (value);
}
