-- Creates the tables for CDManager in a PostgreSQL database.
--
-- Run it connected to the (already created) database, e.g.:
--   createdb -E UTF8 cdmedia && psql -d cdmedia -f createDB-pg.sql
-- (CDManager connects to the name in lower case, like unquoted SQL names)
--
-- The tables correspond to the ones in createDB.sql (for MySQL). The foreign
-- keys are not declared, as (like with MySQL's MyISAM) the program relies on
-- them not being enforced (e.g. films without director).
--
-- After loading entries with explicit ids, run syncSequences-pg.sql (or
-- meson compile -C build syncSequences) to adapt the sequences of the ids.

CREATE TABLE Celebrities
    (name       VARCHAR(64)     NOT NULL,
     id         BIGINT          GENERATED BY DEFAULT AS IDENTITY,
     born       SMALLINT        NOT NULL DEFAULT 0,
     died       SMALLINT        NOT NULL DEFAULT 0,
     PRIMARY KEY (id));
CREATE INDEX celebritiesName ON Celebrities (name);

CREATE TABLE Directors
    (id         BIGINT          NOT NULL,
     PRIMARY KEY (id));

CREATE TABLE Films
    (name       VARCHAR(64)     NOT NULL,
     id         BIGINT          GENERATED BY DEFAULT AS IDENTITY,
     year       SMALLINT        NOT NULL DEFAULT 0,
     director   BIGINT          NOT NULL DEFAULT 0,
     genre      BIGINT          NOT NULL DEFAULT 0,
     type       INT             NOT NULL DEFAULT 0,
     languages  VARCHAR(14)     NOT NULL,
     subtitles  VARCHAR(29)     NOT NULL,
     summary    VARCHAR(1024)   NOT NULL,
     image      BYTEA           NOT NULL,
     PRIMARY KEY (id));
CREATE INDEX filmsName ON Films (name);

CREATE TABLE FilmNames
    (id         BIGINT          NOT NULL,
     name       VARCHAR(64)     NOT NULL,
     language   CHAR(2)         NOT NULL,
     PRIMARY KEY (id, language));

CREATE TABLE Actors
    (id         BIGINT          NOT NULL,
     PRIMARY KEY (id));

CREATE TABLE ActorsInFilms
    (idActor    BIGINT          NOT NULL,
     idFilm     BIGINT          NOT NULL);
CREATE INDEX actorsInFilmsActor ON ActorsInFilms (idActor);

CREATE TABLE Interprets
    (id         BIGINT          NOT NULL,
     PRIMARY KEY (id));

CREATE TABLE Records
    (name       VARCHAR(64)     NOT NULL,
     id         BIGINT          GENERATED BY DEFAULT AS IDENTITY,
     year       SMALLINT        NOT NULL DEFAULT 0,
     interpret  BIGINT          NOT NULL,
     genre      INT             NOT NULL DEFAULT 0,
     PRIMARY KEY (id));
CREATE INDEX recordsName ON Records (name);
CREATE INDEX recordsInterpret ON Records (interpret);

CREATE TABLE Songs
    (name       VARCHAR(64)     NOT NULL,
     id         BIGINT          GENERATED BY DEFAULT AS IDENTITY,
     track      SMALLINT        NOT NULL,
     idRecord   BIGINT          NOT NULL,
     duration   TIME            NOT NULL,
     genre      BIGINT          DEFAULT 0,
     PRIMARY KEY (id));
CREATE INDEX songsName ON Songs (name);
CREATE INDEX songsRecord ON Songs (idRecord);

-- Binary collation, like in MySQL
CREATE TABLE Words
    (word       VARCHAR(32)     COLLATE "C" NOT NULL,
     PRIMARY KEY (word));

CREATE TABLE Articles
    (article    VARCHAR(9)      NOT NULL,
     PRIMARY KEY (article));
