USE CDMedia

DELETE FROM MGenres;
INSERT INTO MGenres VALUES (0, 'Undefined');
INSERT INTO MGenres VALUES (1, 'Comedy');
INSERT INTO MGenres VALUES (2, 'Drama');
INSERT INTO MGenres VALUES (3, 'Musical');
INSERT INTO MGenres VALUES (4, 'Satire');
INSERT INTO MGenres VALUES (5, 'Tragedy');
INSERT INTO MGenres VALUES (6, 'War');

DELETE FROM Genres;
INSERT INTO Genres VALUES (0, 'Undefined');
INSERT INTO Genres VALUES (1, 'Alternative');
INSERT INTO Genres VALUES (2, 'Classic');
INSERT INTO Genres VALUES (3, 'Electronic');
INSERT INTO Genres VALUES (4, 'Gothic');
INSERT INTO Genres VALUES (5, 'Hardcore');
INSERT INTO Genres VALUES (6, 'Industrial');
INSERT INTO Genres VALUES (7, 'Latin');
INSERT INTO Genres VALUES (8, 'Metal');
INSERT INTO Genres VALUES (9, 'Punk');
INSERT INTO Genres VALUES (10, 'Ska');
INSERT INTO Genres VALUES (11, 'Skapunk');

DELETE FROM Words;
INSERT INTO Words VALUES ('A');
INSERT INTO Words VALUES ('Alan');
INSERT INTO Words VALUES ('Alejandro');
INSERT INTO Words VALUES ('Alfonso');
INSERT INTO Words VALUES ('An');
INSERT INTO Words VALUES ('Barbet');
INSERT INTO Words VALUES ('Blake');
INSERT INTO Words VALUES ('Charlie');
INSERT INTO Words VALUES ('Carlos');
INSERT INTO Words VALUES ('Clint');
INSERT INTO Words VALUES ('Costa');
INSERT INTO Words VALUES ('Danny');
INSERT INTO Words VALUES ('David');
INSERT INTO Words VALUES ('Dennis');
INSERT INTO Words VALUES ('Der');
INSERT INTO Words VALUES ('Die');
INSERT INTO Words VALUES ('Das');
INSERT INTO Words VALUES ('Ein');
INSERT INTO Words VALUES ('Eine');
INSERT INTO Words VALUES ('Einer');
INSERT INTO Words VALUES ('Elia');
INSERT INTO Words VALUES ('Emir');
INSERT INTO Words VALUES ('Ethan');
INSERT INTO Words VALUES ('Federico');
INSERT INTO Words VALUES ('Fermin');
INSERT INTO Words VALUES ('González');
INSERT INTO Words VALUES ('Goran');
INSERT INTO Words VALUES ('Guy');
INSERT INTO Words VALUES ('Hazel');
INSERT INTO Words VALUES ('Jaime');
INSERT INTO Words VALUES ('Jaques');
INSERT INTO Words VALUES ('Jean');
INSERT INTO Words VALUES ('Jim');
INSERT INTO Words VALUES ('Joel');
INSERT INTO Words VALUES ('John');
INSERT INTO Words VALUES ('Johann');
INSERT INTO Words VALUES ('Kryzsytof');
INSERT INTO Words VALUES ('La');
INSERT INTO Words VALUES ('Lars');
INSERT INTO Words VALUES ('Las');
INSERT INTO Words VALUES ('Le');
INSERT INTO Words VALUES ('Les');
INSERT INTO Words VALUES ('Lo');
INSERT INTO Words VALUES ('Los');
INSERT INTO Words VALUES ('Louis');
INSERT INTO Words VALUES ('Luc');
INSERT INTO Words VALUES ('Ludwig');
INSERT INTO Words VALUES ('Manu');
INSERT INTO Words VALUES ('Martin');
INSERT INTO Words VALUES ('Mel');
INSERT INTO Words VALUES ('Michael');
INSERT INTO Words VALUES ('Milos');
INSERT INTO Words VALUES ('Nick');
INSERT INTO Words VALUES ('Oliver');
INSERT INTO Words VALUES ('Paul');
INSERT INTO Words VALUES ('Pedro');
INSERT INTO Words VALUES ('Peter');
INSERT INTO Words VALUES ('Pierre');
INSERT INTO Words VALUES ('Quentin');
INSERT INTO Words VALUES ('Richard');
INSERT INTO Words VALUES ('Ridley');
INSERT INTO Words VALUES ('Roberto');
INSERT INTO Words VALUES ('Roland');
INSERT INTO Words VALUES ('Sebastian');
INSERT INTO Words VALUES ('Sidney');
INSERT INTO Words VALUES ('Sinhead');
INSERT INTO Words VALUES ('Stanley');
INSERT INTO Words VALUES ('Stephen');
INSERT INTO Words VALUES ('Steven');
INSERT INTO Words VALUES ('Ted');
INSERT INTO Words VALUES ('Terry');
INSERT INTO Words VALUES ('Todd');
INSERT INTO Words VALUES ('Tom');
INSERT INTO Words VALUES ('Tony');
INSERT INTO Words VALUES ('The');
INSERT INTO Words VALUES ('Un');
INSERT INTO Words VALUES ('Una');
INSERT INTO Words VALUES ('van');
INSERT INTO Words VALUES ('Victor');
INSERT INTO Words VALUES ('von');
